### ISSUE TITLE
unhandled errors in repl.go

### ISSUE THREAD

**Issue by TimSatke** [tomarrell/lbadd#14]
## ⚠ gosec Failed
```
Summary:
   Files: 12
   Lines: 896
   Nosec: 0
  Issues: 1
```
<details><summary>Show Detail</summary>

```
Results:


[/github/workspace/repl.go:46] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > r.executor.execute(instr)


Summary:
   Files: 12
   Lines: 896
   Nosec: 0
  Issues: 1
```
[Code Reference](https://github.com/securego/gosec#available-rules)

</details>

_Originally posted by @github-actions in https://github.com/tomarrell/lbadd/pull/10#issuecomment-570262117_
